Enhancements to configure to handle NERSC systems better

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -106,9 +106,110 @@ EOF
 	return $status
 }
 
+function realcompiler
+{
+    if $CC -V > /dev/null 2>&1; then
+        version=`$CC -V`
+    elif $CC --version > /dev/null 2>&1; then
+        version=`$CC --version`
+    else
+        echo 'Could not determine underlying C/C++ compilers.'
+        echo
+        exit 1
+    fi
+
+    case $version in
+        *Intel*)
+            echo 'Using Intel compilers.'
+            echo
+            compiler=intel
+            ;;
+        *Portland*)
+            echo 'Using Portland Group compilers.'
+            echo
+            compiler=pgi
+            ;;
+        *Cray*)
+            echo 'Using Cray compilers.'
+            echo
+            compiler=cray
+            ;;
+        "*Free Software*")
+            echo 'Using GNU compilers.'
+            echo
+            compiler=gnu
+            ;;
+        *)
+            echo 'Could not determine underlying C/C++ compilers.'
+            echo
+            exit 1
+            ;;
+    esac
+}
+
+function defaultflags
+{
+    #
+    # Set default compiler flags
+    #
+    case $compiler in
+        intel)
+            if [ "x$AR"       = "x" ]; then AR='xiar -crs'; fi
+            if [ "x$CFLAGS"   = "x" ]; then CFLAGS='-openmp -std=c99'; fi
+            if [ "x$CXXFLAGS" = "x" ]; then CXXFLAGS='-openmp -D__STDC_LIMIT_MACROS -Drestrict='; fi
+            if [ "x$DEPS"     = "x" ]; then DEPS='-MT $@ -MD -MP -MF $(DEPDIR)/$(notdir $*).Po'; fi
+            if [ "x$DEFS"     = "x" ]; then DEFS='-D_POSIX_C_SOURCE=200112L'; fi
+            if [ "x$WARN"     = "x" ]; then WARN='-Wall'; fi
+            if [ "x$OPT"      = "x" ]; then OPT=''; fi
+            ;;
+        cray)
+            depstype=stupid
+            if [ "x$AR"       = "x" ]; then AR='ar -crs'; fi
+            if [ "x$CFLAGS"   = "x" ]; then CFLAGS=''; fi
+            if [ "x$CXXFLAGS" = "x" ]; then CXXFLAGS='-D__STDC_LIMIT_MACROS -Drestrict='; fi
+            if [ "x$DEPS"     = "x" ]; then DEPS='-M'; fi
+            if [ "x$DEFS"     = "x" ]; then DEFS='-D_POSIX_C_SOURCE=200112L'; fi
+            if [ "x$WARN"     = "x" ]; then WARN=''; fi
+            if [ "x$OPT"      = "x" ]; then OPT=''; fi
+            ;;
+        pgi)
+            depstype=stupid
+            if [ "x$AR"       = "x" ]; then AR='ar -crs'; fi
+            if [ "x$CFLAGS"   = "x" ]; then CFLAGS='-mp=nonuma -c99'; fi
+            if [ "x$CXXFLAGS" = "x" ]; then CXXFLAGS='-mp=nonuma -D__STDC_LIMIT_MACROS -Drestrict='; fi
+            if [ "x$DEPS"     = "x" ]; then DEPS='-M'; fi
+            if [ "x$DEFS"     = "x" ]; then DEFS='-D_POSIX_C_SOURCE=200112L'; fi
+            if [ "x$WARN"     = "x" ]; then WARN=''; fi
+            if [ "x$OPT"      = "x" ]; then OPT='-fast'; fi
+            ;;
+        gnu)
+            if [ "x$AR"       = "x" ]; then AR='ar -crs'; fi
+            if [ "x$CFLAGS"   = "x" ]; then CFLAGS='-fopenmp -std=c99'; fi
+            if [ "x$CXXFLAGS" = "x" ]; then CXXFLAGS='-fopenmp -D__STDC_LIMIT_MACROS -Drestrict='; fi
+            if [ "x$DEPS"     = "x" ]; then DEPS='-MT $@ -MD -MP -MF $(DEPDIR)/$(notdir $*).Po'; fi
+            if [ "x$DEFS"     = "x" ]; then DEFS='-D_POSIX_C_SOURCE=200112L'; fi
+            if [ "x$WARN"     = "x" ]; then WARN='-Wall'; fi
+            if [ "x$OPT"      = "x" ]; then OPT='-g -O2'; fi
+            ;;
+        *)
+            echo 'No default flags known for given compilers. Make sure that you have set the'
+            echo 'appropriate compiler flags manually.'
+            echo
+            if [ "x$AR"       = "x" ]; then AR='ar -crs'; fi
+            if [ "x$CFLAGS"   = "x" ]; then CFLAGS='-fopenmp -std=c99'; fi
+            if [ "x$CXXFLAGS" = "x" ]; then CXXFLAGS='-fopenmp -D__STDC_LIMIT_MACROS -Drestrict='; fi
+            if [ "x$DEPS"     = "x" ]; then DEPS='-MT $@ -MD -MP -MF $(DEPDIR)/$(notdir $*).Po'; fi
+            if [ "x$DEFS"     = "x" ]; then DEFS='-D_POSIX_C_SOURCE=200112L'; fi
+            if [ "x$WARN"     = "x" ]; then WARN='-Wall'; fi
+            if [ "x$OPT"      = "x" ]; then OPT='-g -O2'; fi
+            ;;
+    esac
+}
+
 #
 # Parse command-line arguments
 #
+depstype=normal
 blasbits=32
 while [ "x$1" != "x" ]; do
 	case $1 in
@@ -154,28 +255,60 @@ done
 #
 # Check for known supercomputer host names
 #
-if (hostname | grep 'edison\|hopper\|carver'); then
-	echo 'Hostname recognized as a NERSC machine'
-	echo
-	
-	host=nersc
-	blaslibs=
-	LDFLAGS=
-	CPPFLAGS=
-	AR='ar -crs'
-	INCLUDES=
-	CC=cc
-	CXX=CC
-	CFLAGS='-fopenmp -std=c99'
-	CXXFLAGS='-fopenmp -D__STDC_LIMIT_MACROS -Drestrict='
-	DEPS='-MT $@ -MD -MP -MF $(DEPDIR)/$(notdir $*).Po'
-	DEFS="-D`echo $NERSC_HOST | tr a-z A-Z` -D_POSIX_C_SOURCE=200112L"
-	WARN='-Wall'
-	OPT='-g -O3'
-	
+if [ "$NERSC_HOST" = "carver" ]; then
+    echo 'Hostname recognized as a NERSC machine'
+    echo
+    host=nersc
+    
+    if [ "x$blaslibs" = "x"]; then
+        if [ "x$MKL" = "x" -o "x$MKL_ILP64" = "x" ]; then
+            echo 'MKL module not loaded and no alternative specified.'
+            echo 'Do "module load mkl" or use the --blas option.'
+            echo
+            exit 1
+        fi
+    fi
+    
+    CC=mpicc
+    CXX=mpiCC
+    realcompiler
+    defaultflags
+    DEFS="$DEFS -DCARVER"
+    
+    if [ $blasbits -eq 32 ]; then
+        blaslibs="$MKL_LP64"
+    else
+        blaslibs="$MKL_ILP64"
+    fi
+    
+elif [ "$NERSC_HOST" = "hopper" -o "$NERSC_HOST" = "edison" ]; then
+    echo 'Hostname recognized as a NERSC machine'
+    echo
+    host=nersc
+    
+    if [ $blasbits -ne 32 ]; then
+        echo '64-bit BLAS not supported on this machine.'
+        echo
+        exit 1
+    fi
+    
+    CC=cc
+    CXX=CC
+    realcompiler
+    defaultflags
+    DEFS="$DEFS -D`echo $NERSC_HOST | tr a-z A-Z`"
+    
+    blaslibs=
+    
 elif (hostname | grep 'surveyor\|intrepid\|challenger\|udawn'); then
 	echo 'Hostname recognized as a BG/P machine'
 	echo
+    
+    if [ $blasbits -ne 32 ]; then
+        echo '64-bit BLAS not supported on this machine.'
+        echo
+        exit 1
+    fi
 	
 	host=bgp
 	blaslibs='-lesslsmpbg -lmass -lxlfmath -lxlf90_r -lxlsmp -lxlomp_ser -lpthread'
@@ -199,6 +332,12 @@ elif (hostname | grep 'surveyor\|intrepid\|challenger\|udawn'); then
 elif (hostname | grep 'vesta\|mira\|cetus\|seq'); then
 	echo 'Hostname recognized as a BG/Q machine'
 	echo
+    
+    if [ $blasbits -ne 32 ]; then
+        echo '64-bit BLAS not supported on this machine.'
+        echo
+        exit 1
+    fi
 	
 	host=bgq
 	blaslibs="-lesslsmpbg -lxlsmp -lxlfmath -lxlf90_r -lm"
@@ -237,73 +376,8 @@ else
 		CXX=mpicxx
 	fi
 	
-	if ! (command -v $CC >/dev/null 2>&1); then
-		echo "MPI C compiler $CC does not exist."
-		echo
-		exit 1
-	fi
-	if ! (command -v $CXX >/dev/null 2>&1); then
-		echo "MPI C++ compiler $CXX does not exist."
-		echo
-		exit 1
-	fi
-	
-	if $CC -show >/dev/null 2>&1; then
-		REALCC=`$CC -show`
-		REALCXX=`$CXX -show`
-	elif $CC -showme >/dev/null 2>&1; then
-		REALCC=`$CC -showme`
-		REALCXX=`$CXX -showme`
-	else
-		echo 'Could not determine underlying C/C++ compilers.'
-		echo
-		exit 1
-	fi
-	
-	echo "CC = $CC"
-	echo "CXX = $CXX"
-	echo "REALCC = $REALCC"
-	echo "REALCXX = $REALCXX"
-	
-	#
-	# Set default compiler flags
-	#
-	if ((echo $REALCC | grep -q icc) && (echo $REALCXX | grep -q icpc)); then
-		if [ "x$AR"       = "x" ]; then AR='xiar -crs'; fi
-		if [ "x$CFLAGS"   = "x" ]; then CFLAGS='-openmp -std=c99'; fi
-		if [ "x$CXXFLAGS" = "x" ]; then CXXFLAGS='-openmp -D__STDC_LIMIT_MACROS -Drestrict='; fi
-		if [ "x$DEPS"     = "x" ]; then DEPS='-MT $@ -MD -MP -MF $(DEPDIR)/$(notdir $*).Po'; fi
-		if [ "x$DEFS"     = "x" ]; then DEFS='-DLinux -D_POSIX_C_SOURCE=200112L'; fi
-		if [ "x$WARN"     = "x" ]; then WARN='-Wall'; fi
-		if [ "x$OPT"      = "x" ]; then OPT='-fast'; fi
-	elif ((echo $REALCC | grep -q gcc) && (echo $REALCXX | grep -q g++)); then
-		if [ "x$AR"       = "x" ]; then AR='ar -crs'; fi
-		if [ "x$CFLAGS"   = "x" ]; then CFLAGS='-fopenmp -std=c99'; fi
-		if [ "x$CXXFLAGS" = "x" ]; then CXXFLAGS='-fopenmp -D__STDC_LIMIT_MACROS -Drestrict='; fi
-		if [ "x$DEPS"     = "x" ]; then DEPS='-MT $@ -MD -MP -MF $(DEPDIR)/$(notdir $*).Po'; fi
-		if [ "x$DEFS"     = "x" ]; then DEFS='-DLinux -D_POSIX_C_SOURCE=200112L'; fi
-		if [ "x$WARN"     = "x" ]; then WARN='-Wall'; fi
-		if [ "x$OPT"      = "x" ]; then OPT='-g -O2'; fi
-	elif ((echo $REALCC | grep -q cc) && (echo $REALCXX | grep -q c++)); then
-		if [ "x$AR"       = "x" ]; then AR='ar -crs'; fi
-		if [ "x$CFLAGS"   = "x" ]; then CFLAGS='-fopenmp -std=c99'; fi
-		if [ "x$CXXFLAGS" = "x" ]; then CXXFLAGS='-fopenmp -D__STDC_LIMIT_MACROS -Drestrict='; fi
-		if [ "x$DEPS"     = "x" ]; then DEPS='-MT $@ -MD -MP -MF $(DEPDIR)/$(notdir $*).Po'; fi
-		if [ "x$DEFS"     = "x" ]; then DEFS='-DLinux -D_POSIX_C_SOURCE=200112L'; fi
-		if [ "x$WARN"     = "x" ]; then WARN='-Wall'; fi
-		if [ "x$OPT"      = "x" ]; then OPT='-g -O2'; fi
-	else
-		echo 'No default flags known for given compilers. Make sure that you have set the'
-		echo 'appropriate compiler flags manually.'
-		echo
-		if [ "x$AR"       = "x" ]; then AR='ar -crs'; fi
-		if [ "x$CFLAGS"   = "x" ]; then CFLAGS='-fopenmp -std=c99'; fi
-		if [ "x$CXXFLAGS" = "x" ]; then CXXFLAGS='-fopenmp -D__STDC_LIMIT_MACROS -Drestrict='; fi
-		if [ "x$DEPS"     = "x" ]; then DEPS='-MT $@ -MD -MP -MF $(DEPDIR)/$(notdir $*).Po'; fi
-		if [ "x$DEFS"     = "x" ]; then DEFS='-DLinux -D_POSIX_C_SOURCE=200112L'; fi
-		if [ "x$WARN"     = "x" ]; then WARN='-Wall'; fi
-		if [ "x$OPT"      = "x" ]; then OPT='-g -O2'; fi
-	fi
+	realcompiler
+	defaultflags
 
 	#
 	# Find BLAS/LAPACK if not already specified
@@ -356,16 +430,13 @@ if [[ $ctfdir != /* && "x$ctfdir" != "x" ]]; then
 	ctfdir=`pwd`/$ctfdir
 fi
 if [ "x$ctfdir" = "x" ]; then
-  read -p "Please specify a CTF directory or press enter to get a CTF clone: " ctfdp
-  if [ -d $ctfdp ]; then
-     ctfdir=$ctfdp
-  fi
-fi
-if [ "x$ctfdir" = "x" ]; then
 	make_ctf=yes
 	ctfdir=$srcdir/ctf
 	if [ ! -d $ctfdir ]; then
-		if (command -v git >/dev/null 2>&1); then
+        read -p "Please specify a CTF directory or press enter to get a CTF clone: " ctfdp
+        if [ -d $ctfdp ]; then
+            ctfdir=$ctfdp
+        elif (command -v git >/dev/null 2>&1); then
 			echo -e "Downloading CTF from external Git repository...\n"
 			if ! git clone git://repo.eecs.berkeley.edu/users/solomon/ctf $ctfdir; then
 				echo -e "Could not download CTF repository.\n"
@@ -422,6 +493,8 @@ CXXFLAGS    = $CXXFLAGS
 FORTRAN_INTEGER_SIZE=$((blasbits/8))
 F77_NAME = $FNAME
 F90_NAME = $FNAME
+
+DEPSTYPE    = $depstype
 
 EOF
 
